# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.16.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.16.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/monetanais/Desktop/ast/asteroide

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/monetanais/Desktop/ast/asteroide

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.16.1/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.16.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/monetanais/Desktop/ast/asteroide/CMakeFiles /Users/monetanais/Desktop/ast/asteroide/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/monetanais/Desktop/ast/asteroide/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ast

# Build rule for target.
ast: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ast
.PHONY : ast

# fast build rule for target.
ast/fast:
	$(MAKE) -f CMakeFiles/ast.dir/build.make CMakeFiles/ast.dir/build
.PHONY : ast/fast

src/Asteroide.o: src/Asteroide.cpp.o

.PHONY : src/Asteroide.o

# target to build an object file
src/Asteroide.cpp.o:
	$(MAKE) -f CMakeFiles/ast.dir/build.make CMakeFiles/ast.dir/src/Asteroide.cpp.o
.PHONY : src/Asteroide.cpp.o

src/Asteroide.i: src/Asteroide.cpp.i

.PHONY : src/Asteroide.i

# target to preprocess a source file
src/Asteroide.cpp.i:
	$(MAKE) -f CMakeFiles/ast.dir/build.make CMakeFiles/ast.dir/src/Asteroide.cpp.i
.PHONY : src/Asteroide.cpp.i

src/Asteroide.s: src/Asteroide.cpp.s

.PHONY : src/Asteroide.s

# target to generate assembly for a file
src/Asteroide.cpp.s:
	$(MAKE) -f CMakeFiles/ast.dir/build.make CMakeFiles/ast.dir/src/Asteroide.cpp.s
.PHONY : src/Asteroide.cpp.s

src/Bullet.o: src/Bullet.cpp.o

.PHONY : src/Bullet.o

# target to build an object file
src/Bullet.cpp.o:
	$(MAKE) -f CMakeFiles/ast.dir/build.make CMakeFiles/ast.dir/src/Bullet.cpp.o
.PHONY : src/Bullet.cpp.o

src/Bullet.i: src/Bullet.cpp.i

.PHONY : src/Bullet.i

# target to preprocess a source file
src/Bullet.cpp.i:
	$(MAKE) -f CMakeFiles/ast.dir/build.make CMakeFiles/ast.dir/src/Bullet.cpp.i
.PHONY : src/Bullet.cpp.i

src/Bullet.s: src/Bullet.cpp.s

.PHONY : src/Bullet.s

# target to generate assembly for a file
src/Bullet.cpp.s:
	$(MAKE) -f CMakeFiles/ast.dir/build.make CMakeFiles/ast.dir/src/Bullet.cpp.s
.PHONY : src/Bullet.cpp.s

src/Game.o: src/Game.cpp.o

.PHONY : src/Game.o

# target to build an object file
src/Game.cpp.o:
	$(MAKE) -f CMakeFiles/ast.dir/build.make CMakeFiles/ast.dir/src/Game.cpp.o
.PHONY : src/Game.cpp.o

src/Game.i: src/Game.cpp.i

.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) -f CMakeFiles/ast.dir/build.make CMakeFiles/ast.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s

.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) -f CMakeFiles/ast.dir/build.make CMakeFiles/ast.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/Texture.o: src/Texture.cpp.o

.PHONY : src/Texture.o

# target to build an object file
src/Texture.cpp.o:
	$(MAKE) -f CMakeFiles/ast.dir/build.make CMakeFiles/ast.dir/src/Texture.cpp.o
.PHONY : src/Texture.cpp.o

src/Texture.i: src/Texture.cpp.i

.PHONY : src/Texture.i

# target to preprocess a source file
src/Texture.cpp.i:
	$(MAKE) -f CMakeFiles/ast.dir/build.make CMakeFiles/ast.dir/src/Texture.cpp.i
.PHONY : src/Texture.cpp.i

src/Texture.s: src/Texture.cpp.s

.PHONY : src/Texture.s

# target to generate assembly for a file
src/Texture.cpp.s:
	$(MAKE) -f CMakeFiles/ast.dir/build.make CMakeFiles/ast.dir/src/Texture.cpp.s
.PHONY : src/Texture.cpp.s

src/fonction.o: src/fonction.cpp.o

.PHONY : src/fonction.o

# target to build an object file
src/fonction.cpp.o:
	$(MAKE) -f CMakeFiles/ast.dir/build.make CMakeFiles/ast.dir/src/fonction.cpp.o
.PHONY : src/fonction.cpp.o

src/fonction.i: src/fonction.cpp.i

.PHONY : src/fonction.i

# target to preprocess a source file
src/fonction.cpp.i:
	$(MAKE) -f CMakeFiles/ast.dir/build.make CMakeFiles/ast.dir/src/fonction.cpp.i
.PHONY : src/fonction.cpp.i

src/fonction.s: src/fonction.cpp.s

.PHONY : src/fonction.s

# target to generate assembly for a file
src/fonction.cpp.s:
	$(MAKE) -f CMakeFiles/ast.dir/build.make CMakeFiles/ast.dir/src/fonction.cpp.s
.PHONY : src/fonction.cpp.s

src/source.o: src/source.cpp.o

.PHONY : src/source.o

# target to build an object file
src/source.cpp.o:
	$(MAKE) -f CMakeFiles/ast.dir/build.make CMakeFiles/ast.dir/src/source.cpp.o
.PHONY : src/source.cpp.o

src/source.i: src/source.cpp.i

.PHONY : src/source.i

# target to preprocess a source file
src/source.cpp.i:
	$(MAKE) -f CMakeFiles/ast.dir/build.make CMakeFiles/ast.dir/src/source.cpp.i
.PHONY : src/source.cpp.i

src/source.s: src/source.cpp.s

.PHONY : src/source.s

# target to generate assembly for a file
src/source.cpp.s:
	$(MAKE) -f CMakeFiles/ast.dir/build.make CMakeFiles/ast.dir/src/source.cpp.s
.PHONY : src/source.cpp.s

src/vaisseau.o: src/vaisseau.cpp.o

.PHONY : src/vaisseau.o

# target to build an object file
src/vaisseau.cpp.o:
	$(MAKE) -f CMakeFiles/ast.dir/build.make CMakeFiles/ast.dir/src/vaisseau.cpp.o
.PHONY : src/vaisseau.cpp.o

src/vaisseau.i: src/vaisseau.cpp.i

.PHONY : src/vaisseau.i

# target to preprocess a source file
src/vaisseau.cpp.i:
	$(MAKE) -f CMakeFiles/ast.dir/build.make CMakeFiles/ast.dir/src/vaisseau.cpp.i
.PHONY : src/vaisseau.cpp.i

src/vaisseau.s: src/vaisseau.cpp.s

.PHONY : src/vaisseau.s

# target to generate assembly for a file
src/vaisseau.cpp.s:
	$(MAKE) -f CMakeFiles/ast.dir/build.make CMakeFiles/ast.dir/src/vaisseau.cpp.s
.PHONY : src/vaisseau.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ast"
	@echo "... src/Asteroide.o"
	@echo "... src/Asteroide.i"
	@echo "... src/Asteroide.s"
	@echo "... src/Bullet.o"
	@echo "... src/Bullet.i"
	@echo "... src/Bullet.s"
	@echo "... src/Game.o"
	@echo "... src/Game.i"
	@echo "... src/Game.s"
	@echo "... src/Texture.o"
	@echo "... src/Texture.i"
	@echo "... src/Texture.s"
	@echo "... src/fonction.o"
	@echo "... src/fonction.i"
	@echo "... src/fonction.s"
	@echo "... src/source.o"
	@echo "... src/source.i"
	@echo "... src/source.s"
	@echo "... src/vaisseau.o"
	@echo "... src/vaisseau.i"
	@echo "... src/vaisseau.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

